title: GHC
description: A business home page starter template for Bootstrap 4 featuring marketing boxes and a full width image header.

baseurl: /ghc-recruitment.github.io
#color-scheme: "mediumseagreen" # the scheme can be any HEX code like "#00aa55"
color-scheme: "#1e1e4a"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
